name: push to docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nmap nikto
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build_push_docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: arjunamhv/arhaminer-back:latest
  deploy:
    needs: build_push_docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Install ssh
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Execute SSH command
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no root@110.239.67.185 "cd arhaminer/ && microk8s.kubectl apply -f arhaminer-back.yaml"
